package zatribune.spring.itextvelocity.reporting;


import com.itextpdf.text.Document;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.tool.xml.XMLWorkerHelper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import zatribune.spring.itextvelocity.db.entities.Report;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.StringReader;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Creates a PDF file from html {@link String} generated by {@link VelocityTemplateParser}
 **/

@Component
public class ITextPdfCreator {

    @Value("${reporting.outputPath}")
    private String outputPath;

    @Value("${reporting.author}")
    private String author;

    @Value("${reporting.creator}")
    private String creator;

    public String createPdf(String html, Report report, Rectangle pageSize){
        PdfWriter pdfWriter;
        // create a new pdf document
        Document pdfDocument=new Document();
        String resultPath=null;
        try {

            // document header attributes
            pdfDocument.addAuthor(author);
            pdfDocument.addCreationDate();
            pdfDocument.addCreator(creator);
            pdfDocument.addTitle(report.getName());
            pdfDocument.setPageSize(pageSize);

            resultPath=String.format("%s%s%s",outputPath,report.getName(),new SimpleDateFormat("yyyyMMddhhmmss'.pdf'").format(new Date()));
            OutputStream file = new FileOutputStream(new File(resultPath));

            pdfWriter = PdfWriter.getInstance(pdfDocument, file);

            // open document
            pdfDocument.open();

            XMLWorkerHelper xmlWorkerHelper = XMLWorkerHelper.getInstance();
            xmlWorkerHelper.getDefaultCssResolver(true);

            xmlWorkerHelper.parseXHtml(pdfWriter, pdfDocument, new StringReader(html));
            // close the document
            pdfDocument.close();
            // close the writer
            pdfWriter.close();


            System.out.println("PDF generated successfully");
        } catch (Exception e) {
            e.printStackTrace();
        }

        return resultPath;
    }
}
